package com.sandbox.model;

public enum GameMode {
	NONE, ALL_PICK, CAPTAINS_MODE, RANDOM_DRAFT, SINGLE_DRAFT, ALL_RANDOM, INTRO, DIRETIDE, REVERSE_CAPTAINS_MODE, THE_GREEVILING, TUTORIAL, MID_ONLY, LEAST_PLAYED, NEW_PLAYER_POOL, COMPENDIUM_MATCHMAKING;
}
